### ISSUE TITLE
[SPIKE] Investigate Death 'Catalysts'

### ISSUE THREAD

**Issue by sklei2** [sklei2/DeathClock#3]
This could help with the algorithm.

**Comment by kleenip** [comment]
1. Heart disease
2. Cancer (malignant neoplasms)
3. Chronic lower respiratory disease
4. Accidents (unintentional injuries)
5. Stroke (cerebrovascular diseases)
6. Alzheimer's disease
7. Diabetes
8. Influenza and pneumonia
9. Kidney disease (nephritis, nephrotic syndrome, and nephrosis)
10. Suicide

https://www.medicalnewstoday.com/articles/282929.php
